openapi: 3.1.0
info:
  title: STD23011-TD1
  version: 1.0.0
servers:
  - url: 'http://localhost.std23011.com'
paths:
  /customers:
    get:
      responses:
        '200':
          description: A list of customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customer'

components:
  schemas:
    customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer